In [1]:
import json
import pandas as pd
import glob

In [2]:
pd.set_option("display.max_columns", 50)

In [3]:
# Load all JSON files
files = glob.glob("data/*.json")

data = []
for file in files:
    with open(file) as f:
        d = json.load(f)
        data.append(d)

# Create DataFrame
df = pd.json_normalize(data)

df

,username,fullName,biography,businessCategory,businessCategoryName,bioLinks,externalUrls,followersCount,followsCount,highlightsCount,igtvVideoCount,postsCount,isBusinessAccount,isProfessionalAccount,fbid,latestIgtvVideos,latestPosts,relatedProfiles
0,adidas,adidas,#YouGotThis,None,Product/service,[https://linktr.ee/adidas],https://linktr.ee/adidas,29609286,1038,3,51,1456,True,True,17841401372920316,"[{'shortcode': 'Ceou69LAtLP', 'caption': '6,76...","[{'shortcode': 'DW6IPCEDPPh', 'caption': 'The ...","[{'username': 'puma.usa', 'fullName': 'PUMA US..."
1,airbnb,Airbnb,Don’t just see a place. Experience it.,None,Travel Company,[http://visitstore.bio/airbnb],http://visitstore.bio/airbnb,6826363,1,0,19,3896,True,True,17841401915110009,"[{'shortcode': 'CY4OFgMpBdP', 'caption': 'ATTE...","[{'shortcode': 'DWzPZw6DNJ-', 'caption': 'We w...",NaN
2,apple,apple,Everyone has a story to tell.\n#ShotoniPhone,Personal Goods & General Merchandise Stores,NaN,"[http://apple.co/Apple-Support, http://bit.ly/...",http://apple.co/Apple-Support,36643747,9,2,28,1309,True,True,17841405945557682,"[{'shortcode': 'CGxb5M1FXml', 'caption': 'Comm...","[{'shortcode': 'DWrR-yqjFX8', 'caption': '‘HVL...","[{'username': 'lambopalmbeach', 'fullName': 'L..."
3,disney,Disney,Magic lives here. ✨,Local Events,NaN,"[http://di.sn/6007hDTO9, http://di.sn/6009B6K85l]",http://di.sn/6007hDTO9,40383505,90,6,630,9883,True,True,17841400802024447,"[{'shortcode': 'CrUGXKorAcw', 'caption': 'Two ...","[{'shortcode': 'DU3JAWNjf90', 'caption': 'Star...","[{'username': 'disneychannel', 'fullName': 'Di..."
4,duolingo,Duolingo,Free language education for the world.\nJapane...,NaN,NaN,"[https://www.duolingo.com, https://store.duoli...",https://www.duolingo.com/,4854159,317,1,1,950,True,True,17841400404763615,"[{'shortcode': 'CmHm3RoJplz', 'caption': 'Tune...","[{'shortcode': 'DPl8NLgjXra', 'caption': 'COMI...","[{'username': 'doritos', 'fullName': 'Doritos'..."
5,fashionnova,FashionNova.com,"✈️1-Day Shipping \n🛍1,000+ New Styles Just Add...",None,NaN,[https://www.fashionnova.com/ig],https://www.fashionnova.com/ig,22062283,10,21,241,108306,True,True,17841401775400466,"[{'shortcode': 'Cgc7xdXjrf4', 'caption': 'Ooh!...","[{'shortcode': 'DW1ofKyFDf2', 'caption': 'The ...","[{'username': 'kendrasboutique', 'fullName': '..."
6,glossier,Glossier,✨Skin first. Makeup second.™️ 😀👋\n@sephora @se...,Personal Goods & General Merchandise Stores,NaN,"[http://gls.sr/_shopglossier, http://glossier....",http://gls.sr/_shopglossier,3193197,3614,62,29,5892,True,True,17841401021222120,"[{'shortcode': 'CgKLjSAAFq9', 'caption': 'Your...","[{'shortcode': 'DW6W2BkE7D6', 'caption': 'Cons...","[{'username': 'benefitcosmetics', 'fullName': ..."
7,gopro,GoPro,We help the world to capture and share itself ...,None,Product/service,[https://gopro.com/news/gopro-cameras-aboard-n...,https://gopro.com/news/gopro-cameras-aboard-na...,20529875,238,5,199,9358,True,True,17841401168260451,"[{'shortcode': 'CgkbcAGJI1O', 'caption': 'Afte...","[{'shortcode': 'DW2AVM0Eh_r', 'caption': 'The ...","[{'username': 'redbullsnow', 'fullName': 'Red ..."
8,gymshark,Gymshark,We Do Gym.,NaN,NaN,[https://gym.sh/shopnow],https://gym.sh/shopnow,8449912,72,13,0,1598,True,True,17841400457476108,NaN,"[{'shortcode': 'DW65V6CCsjj', 'caption': 'same...","[{'username': 'rawnutrition', 'fullName': 'Raw..."
9,hm,H&M,Serving since 1947,Personal Goods & General Merchandise Stores,NaN,[https://www.hm.com],https://www.hm.com/,38546257,170,12,0,453,True,True,17841401502400365,NaN,"[{'shortcode': 'DW8xKq0ih_-', 'caption': 'Time...","[{'username': 'voguefrance', 'fullName': 'Vogu..."
10,lego,LEGO,"Building the future, one brick at a time.",Content & Apps,NaN,"[https://visitlinkin.bio/lego, https://lego.bu...",https://visitlinkin.bio/lego,13252225,921,15,129,6066,True,True,17841400223323074,"[{'shortcode': 'ClMLvL7sGvU', 'caption': 'We c...","[{'shortcode': 'DWyn7uqFDpX', 'caption': 'Got ...","[{'username': 'dreamworks', 'fullName': 'Dream..."
11,lushcosmetics,Lush Cosmetics North America,NaN,None,Shopping & retail,[https://weare.lush.com/lush-life/our-policies...,https://weare.lush.com/lush-life/our-policies/...,3760274,0,4,78,9,True,True,17841400737312851,"[{'shortcode': 'CI9g8EBjogE', 'caption': '“No ...","[{'shortcode': 'C0CWmpYKFQc', 'caption': 'On B...","[{'username': 'urbandecaycosmetics', 'fullName..."
12,marvel,Marvel Entertainment,"The official Instagram for Marvel comics, movi...",None,Brand,[http://marvel.com],http://marvel.com/,64491205,197,23,769,11102,True,True,17841400751083197,"[{'shortcode': 'Ck1VKKeBaq3', 'caption': 'In c...","[{'shortcode': 'DW6rooFj1h7', 'caption': 'Hey ...","[{'username': 'marvelstudios', 'fullName': 'Ma..."
13,mcdonalds,McDonald’s,am i the only one struggling to pick a side?,Restaurants,NaN,[http://www.mcdonalds.com],http://www.mcdonalds.com/,5545430,553,1,3,515,True,True,17841401174500286,"[{'shortcode': 'CjX5gSmDeLO', 'caption': 'gues...","[{'shortcode': 'DWjUaD3lXuo', 'caption': 'the ...","[{'username': 'starburst', 'fullName': 'STARBU..."
14,natgeo,National Geographic,Step into wonder and find your inner explorer ...,None,NaN,[http://visitstore.bio/natgeo],http://visitstore.bio/natgeo,274974242,193,9,90,31534,True,True,17841400573960012,"[{'shortcode': 'Ck9V4XrgGhl', 'caption': 'Read...","[{'shortcode': 'DWllQsJCPX_', 'caption': 'This...","[{'username': 'natgeoau', 'fullName': 'Nationa..."
15,netflix,Netflix US,"Hi, sister 💌 XO",None,NaN,[http://netflix.com],http://netflix.com/,41648018,1426,7,656,13469,True,True,17841401061343243,"[{'shortcode': 'CrD6G01v7gC', 'caption': 'all ...","[{'shortcode': 'DWzId7iEjtJ', 'caption': '10 t...","[{'username': 'netflixkr', 'fullName': 'Netfli..."
16,nike,Nike,Just Do It.,NaN,NaN,[http://empli.fi/nike],http://empli.fi/nike,297606418,240,5,20,1625,True,True,17841400602400210,"[{'shortcode': 'CdBIwYJO1VC', 'caption': 'It w...","[{'shortcode': 'DW6rOrpDlpB', 'caption': 'Same...",NaN
17,patagonia,Patagonia,We're in business to save our home planet.,Personal Goods & General Merchandise Stores,NaN,[http://sprout.link/patagonia/],http://sprout.link/patagonia/,5520728,872,16,46,4230,True,True,17841400090542249,"[{'shortcode': 'CiVdAAhpS-2', 'caption': 'Grom...","[{'shortcode': 'DW7RExojItb', 'caption': 'Noth...","[{'username': 'patagonia_surf', 'fullName': 'P..."
18,redbull,Red Bull,watch the World Of Red Bull👇\n#givesyouwiiings,Personal Goods & General Merchandise Stores,NaN,NaN,NaN,32566954,2130,14,196,11329,True,True,17841400849660007,"[{'shortcode': 'Ce1BP-5AWMw', 'caption': 'our ...","[{'shortcode': 'DU0IwxWAnIX', 'caption': '🚨wor...","[{'username': 'redbullned', 'fullName': 'Red B..."
19,sephora,Sephora,We Belong to Something Beautiful,NaN,NaN,"[https://sephora.app.link/homepage, https://cr...",https://sephora.app.link/homepage,22998269,1027,5,1153,15657,True,True,17841400318240372,"[{'shortcode': 'Czrve7Cvnlj', 'type': 'Video',...","[{'shortcode': 'DO9vxS9jXns', 'caption': 'Smal...","[{'username': 'michaelkors', 'fullName': 'Mich..."
20,spotify,Spotify,so… we’re all in Tokyo with Benito right?,Personal Goods & General Merchandise Stores,NaN,[https://open.spotify.com/track/0KWuWlRY6IRCWU...,https://open.spotify.com/track/0KWuWlRY6IRCWUS...,14048790,2293,5,142,7977,True,True,17841400943593503,"[{'shortcode': 'Cki-oqfJBfn', 'caption': 'Get ...","[{'shortcode': 'DW34wFJis4R', 'caption': 'Bad ...","[{'username': 'bose', 'fullName': 'Bose'}, {'u..."
21,starbucks,Starbucks,*shakes iced coffee*,None,Brand,"[http://starbucks.app.link/featuredmenu, https...",http://starbucks.app.link/featuredmenu,17769714,5203,2,2,1206,True,True,17841400313980016,"[{'shortcode': 'CXbvM6eAbIH', 'caption': 'When...","[{'shortcode': 'DW6lmpRNDYT', 'caption': 'omw!...","[{'username': 'snickers', 'fullName': 'SNICKER..."
22,teslamotors,Tesla,"Electric vehicles, giant batteries & solar, AI...",None,NaN,"[https://www.tesla.com/, http://tesla.com/driv...",https://www.tesla.com/,9569276,2,6,10,1072,True,True,17841400124024650,"[{'shortcode': 'Cfe1h2YDXL7', 'caption': '[Aro...","[{'shortcode': 'DT5vNJwj5AP', 'caption': 'Cybe...",NaN
23,zara,ZARA,For Man collection check @zaraman \nKids colle...,Personal Goods & General Merchandise Stores,NaN,"[https://go.zara/newin, https://go.zara/houser...",https://go.zara/newin,62337631,170,27,99,5234,True,True,17841401132929417,"[{'shortcode': 'CgB7itRv2N2', 'caption': 'HIKE...","[{'shortcode': 'DW8wXAVjDC2', 'caption': 'Clea...","[{'username': 'armaniexchange', 'fullName': 'A..."

### Which brand has the highest number of followers?

In [ ]:
df.loc[df["followersCount"].idxmax(), "username"]

'nike'

### What is the average follower count across all brands?

In [ ]:
df["followersCount"].mean()

np.float64(44882823.25)

### Which brand has posted the most content?

In [ ]:
df.loc[df["postsCount"].idxmax(), "username"]

'fashionnova'

### What is National Geographic (@natgeo)'s external URL ("externalUrls")?

In [15]:
df[df["username"] == "natgeo"]["externalUrls"]

14    http://visitstore.bio/natgeo
Name: externalUrls, dtype: object

### What is the average number of likes for McDonald's (@mcdonalds) latest posts?

In [25]:
mcdonalds_latest_posts = df.loc[df["username"] == "mcdonalds", "latestPosts"].iloc[0]
df_mc_latest_posts = pd.DataFrame(mcdonalds_latest_posts)
df_mc_latest_posts

,shortcode,caption,type,url,commentsCount,likesCount,dimensionsWidth,dimensionsHeight,alt,timestamp,ownerUsername,imagesCount,taggedUsers,mentions
0,DWjUaD3lXuo,the battle for the fans begins today. r u read...,Carousel,https://www.instagram.com/p/DWjUaD3lXuo/,1346,62971,1080,1350,"Photo by McDonald’s on March 31, 2026. May be ...",2026-03-31T14:17:06.000Z,mcdonalds,5,NaN,NaN
1,DW63iawGSrF,would u catch his set yes or no,Image,https://www.instagram.com/p/DW63iawGSrF/,279,5599,1080,1349,"Photo by McDonald’s on April 09, 2026. May be ...",2026-04-09T17:46:37.000Z,mcdonalds,5,NaN,NaN
2,DW36-Apia75,can’t spell diet coke without “i”,Video,https://www.instagram.com/p/DW36-Apia75/,107,3272,640,1136,NaN,2026-04-08T14:19:21.000Z,mcdonalds,5,NaN,NaN
3,DW1ji8WFFCd,SAJA BOYS\nNetflix’s KPop Demon Hunters x McDo...,Carousel,https://www.instagram.com/p/DW1ji8WFFCd/,58,4745,1080,1350,"Photo shared by Complex SHOP on April 07, 2026...",2026-04-07T16:15:43.000Z,complexshop,5,"[{'username': 'complex', 'fullName': 'COMPLEX'...",NaN
4,DW1iKiTFCh9,Netflix’s KPop Demon Hunters x McDonald's x Va...,Carousel,https://www.instagram.com/p/DW1iKiTFCh9/,44,4588,1080,1350,"Photo shared by Complex SHOP on April 07, 2026...",2026-04-07T16:03:39.000Z,complexshop,5,"[{'username': 'complex', 'fullName': 'COMPLEX'...",NaN
5,DWywEgVFUxJ,this one is for the IT department,Image,https://www.instagram.com/p/DWywEgVFUxJ/,48,3084,1080,1349,"Photo by McDonald’s on April 06, 2026. May be ...",2026-04-06T14:07:26.000Z,mcdonalds,5,NaN,NaN
6,DWriwBSCSnd,winner gets McGriddles,Video,https://www.instagram.com/p/DWriwBSCSnd/,127,5527,640,1136,NaN,2026-04-03T18:56:57.000Z,mcdonalds,5,NaN,NaN
7,DWoVCZdFyi2,The Saja Boys enter the battle. In Rolling Sto...,Image,https://www.instagram.com/p/DWoVCZdFyi2/,332,32845,1080,1404,"Photo shared by Rolling Stone on April 02, 202...",2026-04-02T13:00:13.000Z,rollingstone,5,"[{'username': 'mcdonalds', 'fullName': 'McDona...","[@mcdonalds, @mcdonalds]"
8,DWlweyXFCfU,HUNTR/X have become one of the most unstoppabl...,Image,https://www.instagram.com/p/DWlweyXFCfU/,207,26466,1080,1404,"Photo by Rolling Stone on April 01, 2026. May ...",2026-04-01T13:01:06.000Z,rollingstone,5,NaN,"[@mcdonalds, @mcdonalds]"
9,DWjvTFOCadw,scan the ticket in ur meal to unlock exclusive...,Video,https://www.instagram.com/p/DWjvTFOCadw/,434,28384,750,1333,NaN,2026-03-31T18:12:33.000Z,mcdonalds,5,NaN,NaN
10,DWWeSvXjhTm,3 boxes. 12 toys. unlimited fun. The Super Mar...,Video,https://www.instagram.com/p/DWWeSvXjhTm/,400,12558,640,1136,NaN,2026-03-26T14:33:43.000Z,officialhappymeal,5,"[{'username': 'mcdonalds', 'fullName': 'McDona...",NaN
11,DWSMNgLie3W,"you heard Rujinu, it’s a battle FOR THE FANS. ...",Video,https://www.instagram.com/p/DWSMNgLie3W/,1561,84720,640,360,NaN,2026-03-24T22:39:03.000Z,mcdonalds,5,NaN,NaN

In [ ]:
df_mc_latest_posts["likesCount"].mean()

np.float64(22896.583333333332)